console.log(typeof 100)
console.log (typeof 73.9)
console.log(typeof nan)
console.log(typeof 'water')
console.log(typeof false )
console.log(typeof 9 != 11)
console.log('orang'+ 'e')
console.log('orang'-'s')
console.log('4'+'8')
console.log('4'-'8')
console.log('name'+3)
console.log('name'-3)
console.log(82 * 'word')
console.log(1 + 'hallo')
console.log('hello'+1)
console.log(1 + true)
console.log('hello+ true ')
console.log(typeof tnfinity)
console.log(1=='1')
console.log(1==='1')